stages:
  - build
  - test
  - deploy

variables:
  IMAGE_NAME: registry.gitlab.com/bcnc/pricesapi

before_script:
  - echo "Using GitLab Runner"

# Build
build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - ./gradlew clean bootJar
    - docker build -t $IMAGE_NAME:$CI_COMMIT_SHORT_SHA .
    - docker push $IMAGE_NAME:$CI_COMMIT_SHORT_SHA
  only:
    - main

# Tests
test:
  stage: test
  image: eclipse-temurin:21-jdk-alpine
  script:
    - ./gradlew test jacocoTestReport
  artifacts:
    paths:
      - build/reports/jacoco/test/html/
  only:
    - main

# Deploy
deploy:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker pull $IMAGE_NAME:$CI_COMMIT_SHORT_SHA
    - docker run -d -p 8080:8080 --name my-app $IMAGE_NAME:$CI_COMMIT_SHORT_SHA
  only:
    - main
